
import java.awt.CardLayout;
import java.util.Arrays;

/**
 *
 * @author Group 2
 */
public class CalendarGUI extends javax.swing.JFrame {

    /**
     * Creates new form CalendarGUI
     */
    public CalendarGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        GUIPanel = new javax.swing.JPanel();
        instructionsLabel = new javax.swing.JLabel();
        monthTextField = new javax.swing.JTextField();
        monthLabel = new javax.swing.JLabel();
        calendarDisplayPanel = new javax.swing.JPanel();
        oneMonthPanel = new javax.swing.JPanel();
        oneMonthLabel = new javax.swing.JLabel();
        javax.swing.JPanel threeMonthPanel = new javax.swing.JPanel();
        threeMonthLabel = new javax.swing.JLabel();
        twelveMonthPanel = new javax.swing.JPanel();
        twelveMonthLabel = new javax.swing.JLabel();
        typeComboBox = new javax.swing.JComboBox<>();
        yearLabel = new javax.swing.JLabel();
        yearTextField = new javax.swing.JTextField();
        updateButton = new javax.swing.JButton();
        typeLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calendar Generator");

        GUIPanel.setLayout(new java.awt.GridBagLayout());

        instructionsLabel.setText("Enter the desired calendar type, starting month, and year below, then press \"Update\" to generate the new calendar.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        GUIPanel.add(instructionsLabel, gridBagConstraints);

        monthTextField.setColumns(10);
        monthTextField.setText("January");
        monthTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monthTextFieldActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        GUIPanel.add(monthTextField, gridBagConstraints);

        monthLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        monthLabel.setText("Starting Month: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        GUIPanel.add(monthLabel, gridBagConstraints);

        calendarDisplayPanel.setLayout(new java.awt.CardLayout());

        oneMonthPanel.setPreferredSize(new java.awt.Dimension(0, 0));
        oneMonthPanel.setLayout(new java.awt.GridBagLayout());

        oneMonthLabel.setText("oneMonth");
        oneMonthPanel.add(oneMonthLabel, new java.awt.GridBagConstraints());

        calendarDisplayPanel.add(oneMonthPanel, "1 Month");

        threeMonthPanel.setLayout(new java.awt.GridBagLayout());

        threeMonthLabel.setText("threeMonth");
        threeMonthPanel.add(threeMonthLabel, new java.awt.GridBagConstraints());

        calendarDisplayPanel.add(threeMonthPanel, "3 Months");

        twelveMonthPanel.setLayout(new java.awt.GridBagLayout());

        twelveMonthLabel.setText("twelveMonth");
        twelveMonthPanel.add(twelveMonthLabel, new java.awt.GridBagConstraints());
        twelveMonthLabel.getAccessibleContext().setAccessibleName("12 Months");

        calendarDisplayPanel.add(twelveMonthPanel, "12 Months");

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        GUIPanel.add(calendarDisplayPanel, gridBagConstraints);

        typeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 Month", "3 Months", "12 Months" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        GUIPanel.add(typeComboBox, gridBagConstraints);

        yearLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        yearLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        yearLabel.setText("Year: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        GUIPanel.add(yearLabel, gridBagConstraints);

        yearTextField.setText("2019");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        GUIPanel.add(yearTextField, gridBagConstraints);

        updateButton.setText("Update");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        GUIPanel.add(updateButton, gridBagConstraints);

        typeLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        typeLabel.setText("Calendar Type: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        GUIPanel.add(typeLabel, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(GUIPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 644, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(GUIPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void monthTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monthTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_monthTextFieldActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        CardLayout cl = (CardLayout) (calendarDisplayPanel.getLayout());
        cl.show(calendarDisplayPanel, 
                typeComboBox.getItemAt(typeComboBox.getSelectedIndex()));
        calendarDisplayPanel.repaint();
        calendarDisplayPanel.revalidate();
    }//GEN-LAST:event_updateButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalendarGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalendarGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalendarGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalendarGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        // just testing the Calender.generate(int month, int year) method
        // Calendar.generate(12, 2019) should generate the calendar for 
        // December 2019
        System.out.println(Arrays.toString(Calendar.generate(12, 2019)));
        // make sure array is size 42 (6 weeks of 7 days each
        System.out.println(Calendar.generate(12,2019).length);

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalendarGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel GUIPanel;
    private javax.swing.JPanel calendarDisplayPanel;
    private javax.swing.JLabel instructionsLabel;
    private javax.swing.JLabel monthLabel;
    private javax.swing.JTextField monthTextField;
    private javax.swing.JLabel oneMonthLabel;
    private javax.swing.JPanel oneMonthPanel;
    private javax.swing.JLabel threeMonthLabel;
    private javax.swing.JLabel twelveMonthLabel;
    private javax.swing.JPanel twelveMonthPanel;
    private javax.swing.JComboBox<String> typeComboBox;
    private javax.swing.JLabel typeLabel;
    private javax.swing.JButton updateButton;
    private javax.swing.JLabel yearLabel;
    private javax.swing.JTextField yearTextField;
    // End of variables declaration//GEN-END:variables
}
